name: "Deploy MTFU"
on:
  push:
    branches:
       - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código
      uses: actions/checkout@v4
      
    - name: Copiar arquivo para VPS MTFU
      uses: appleboy/scp-action@v0.1.7
      with:
        host: "191.101.18.75"
        username: "root"
        password: ${{ secrets.PASSWORD }}
        # key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/MTFU-WebApp"

    - name: Build e deploy da aplicação
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: "191.101.18.75"
        username: "root"
        password: ${{ secrets.PASSWORD }}
        # key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /MTFU-WebApp
          npm i
          npm run build 
          cp -r dist/* /var/www/html